version: '3.7'
services:
  grafana:
    image: grafana/grafana:lastest
    ports:
     - "3000:3000/tcp"
     - "3000:3000/udp"
    user: "0"
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"] 
    environment:
      - GF_SERVER_ROOT_URL=http://Your_ip:3000
      - GF_SECURITY_ADMIN_PASSWORD=finchina
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app,grafana-clock-panel
    volumes:
      - $PWD/data:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    container_name: grafana
