{
 "title": "Zabbix Top",
 "tags": [ "zabbix_new" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Group", "label": "组别", "query": "*" }
  ]
 },
 "panels": [
  {
   "title": "$Group-Linux 可用内存 TOP",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "bottom",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "5",
        "median"
       ],
       "text": "bottom(5, median)"
      }
     ],
     "group": { "filter": "$Group-Linux" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$Group-Linux CPU 使用率 TOP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "bottom",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "5",
        "median"
       ],
       "text": "bottom(5, median)"
      }
     ],
     "group": { "filter": "$Group-Linux" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "CPU idle time" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$Group-Windows CPU使用率 TOP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$Group-Windows" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "CPU使用率百分比" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$Group-Windows 可用内存 TOP",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "def": {
        "category": "Filter",
        "defaultParams": [
         5,
         "avg"
        ],
        "name": "bottom",
        "params": [
         { "name": "number", "type": "int" },
         {
          "name": "value",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "5",
        "median"
       ],
       "text": "bottom(5, median)"
      }
     ],
     "group": { "filter": "$Group-Windows" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "Free memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$Group-Linux 入口流量 TOP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "$Group-Linux" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/Incoming.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$Group-Linux 出口流量 TOP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "$Group-Linux" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/Outgoing .*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$Group-Windows 入口流量 TOP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "$Group-Windows" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "Incoming network traffic on Intel(R) PRO/1000 MT Network Connection"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "$Group-Windows 出口流量 TOP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "$Group-Windows" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "Outgoing network traffic on Intel(R) PRO/1000 MT Network Connection"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": {
    "0": { "refId": "A" },
    "Zabbix": {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "proxy": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   }
  }
 ]
}